### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by gedw99** [configwizard/mergemovie#1]
any ideas what I am doing wrong.

I making a makefile for this and can PR it in.

```sh
npm run dev

> frontend@0.0.0 dev
> vite


  VITE v3.2.7  ready in 67 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
3:29:08 PM [vite] Internal server error: Failed to resolve import "../wailsjs/go/main/Downloader" from "src/main.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/apple/workspace/go/src/github.com/gedw99/kanka-cloudflare/modules/viideo/video-stream-downloader/mergemovie/frontend/src/main.js:4:106
  2  |  import './app.css';
  3  |  
  4  |  import {DiscoverM3u8MasterLinks, RetrieveVariants, Download, DirectDownload, OpenInDefaultBrowser} from '../wailsjs/go/main/Downloader';
     |                                                                                                           ^
  5  |  import {EventsOn} from '../wailsjs/runtime/runtime'
  6  |  
      at formatError (file:///Users/apple/workspace/go/src/github.com/gedw99/kanka-cloudflare/modules/viideo/video-stream-downloader/mergemovie/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40358:46)
      at TransformContext.error (file:///Users/apple/workspace/go/src/github.com/gedw99/kanka-cloudflare/modules/viideo/video-stream-downloader/mergemovie/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40354:19)
      at normalizeUrl (file:///Users/apple/workspace/go/src/github.com/gedw99/kanka-cloudflare/modules/viideo/video-stream-downloader/mergemovie/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:37222:33)
      at async TransformContext.transform (file:///Users/apple/workspace/go/src/github.com/gedw99/kanka-cloudflare/modules/viideo/video-stream-downloader/mergemovie/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:37355:47)
      at async Object.transform (file:///Users/apple/workspace/go/src/github.com/gedw99/kanka-cloudflare/modules/viideo/video-stream-downloader/mergemovie/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:40611:30)
      at async loadAndTransform (file:///Users/apple/workspace/go/src/github.com/gedw99/kanka-cloudflare/modules/viideo/video-stream-downloader/mergemovie/frontend/node_modules/vite/dist/node/chunks/dep-2faf2534.js:36998:29)
```

**Comment by gedw99** [comment]
got it

go install github.com/wailsapp/wails/v2/cmd/wails@latest

wails dev

wails build
